package com.zhangweinan.dao;

import com.zhangweinan.dao.objects.AddressDO;
import java.util.List;

public interface AddressDOMapper extends AddressDOMapperBase{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lego_address
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lego_address
     *
     * @mbggenerated
     */
    int insert(AddressDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lego_address
     *
     * @mbggenerated
     */
    AddressDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lego_address
     *
     * @mbggenerated
     */
    List<AddressDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lego_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AddressDO record);
}