package com.zhangweinan.dao;

import com.zhangweinan.dao.objects.OrderDO;
import java.util.List;

public interface OrderDOMapper extends OrderDOMapperBase{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lego_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lego_order
     *
     * @mbggenerated
     */
    int insert(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lego_order
     *
     * @mbggenerated
     */
    OrderDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lego_order
     *
     * @mbggenerated
     */
    List<OrderDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lego_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderDO record);
}