package com.zhangweinan.dao;

import com.zhangweinan.dao.objects.ProductDO;
import java.util.List;

public interface ProductDOMapper extends ProductDOMapperBase{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lego_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lego_product
     *
     * @mbggenerated
     */
    int insert(ProductDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lego_product
     *
     * @mbggenerated
     */
    ProductDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lego_product
     *
     * @mbggenerated
     */
    List<ProductDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lego_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductDO record);
}