package com.zhangweinan.dao;

import com.zhangweinan.dao.objects.RepertoryDO;
import java.util.List;

public interface RepertoryDOMapper extends RepertoryDOMapperBase{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lego_product_repertory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lego_product_repertory
     *
     * @mbggenerated
     */
    int insert(RepertoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lego_product_repertory
     *
     * @mbggenerated
     */
    RepertoryDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lego_product_repertory
     *
     * @mbggenerated
     */
    List<RepertoryDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lego_product_repertory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RepertoryDO record);
}