package com.zhangweinan.dao.objects;

import java.util.Date;

public class RepertoryDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lego_product_repertory.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lego_product_repertory.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lego_product_repertory.gmt_modify
     *
     * @mbggenerated
     */
    private Date gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lego_product_repertory.size
     *
     * @mbggenerated
     */
    private Integer size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lego_product_repertory.sold_count
     *
     * @mbggenerated
     */
    private Integer soldCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lego_product_repertory.for_sale_count
     *
     * @mbggenerated
     */
    private Integer forSaleCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lego_product_repertory.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lego_product_repertory.id
     *
     * @return the value of lego_product_repertory.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lego_product_repertory.id
     *
     * @param id the value for lego_product_repertory.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lego_product_repertory.gmt_create
     *
     * @return the value of lego_product_repertory.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lego_product_repertory.gmt_create
     *
     * @param gmtCreate the value for lego_product_repertory.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lego_product_repertory.gmt_modify
     *
     * @return the value of lego_product_repertory.gmt_modify
     *
     * @mbggenerated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lego_product_repertory.gmt_modify
     *
     * @param gmtModify the value for lego_product_repertory.gmt_modify
     *
     * @mbggenerated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lego_product_repertory.size
     *
     * @return the value of lego_product_repertory.size
     *
     * @mbggenerated
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lego_product_repertory.size
     *
     * @param size the value for lego_product_repertory.size
     *
     * @mbggenerated
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lego_product_repertory.sold_count
     *
     * @return the value of lego_product_repertory.sold_count
     *
     * @mbggenerated
     */
    public Integer getSoldCount() {
        return soldCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lego_product_repertory.sold_count
     *
     * @param soldCount the value for lego_product_repertory.sold_count
     *
     * @mbggenerated
     */
    public void setSoldCount(Integer soldCount) {
        this.soldCount = soldCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lego_product_repertory.for_sale_count
     *
     * @return the value of lego_product_repertory.for_sale_count
     *
     * @mbggenerated
     */
    public Integer getForSaleCount() {
        return forSaleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lego_product_repertory.for_sale_count
     *
     * @param forSaleCount the value for lego_product_repertory.for_sale_count
     *
     * @mbggenerated
     */
    public void setForSaleCount(Integer forSaleCount) {
        this.forSaleCount = forSaleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lego_product_repertory.product_id
     *
     * @return the value of lego_product_repertory.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lego_product_repertory.product_id
     *
     * @param productId the value for lego_product_repertory.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
}